// AUTO-GENERATED: import data - Osoby z numerami (20.02.2026)
// Zrodlo: C:\Users\stech\...\2026-09\20.02.2026_Osoby z numerami.xlsx
// Kolumna B (imiona i nazwiska) -> zakladka Osoby kolumna B
// Kolumna D (telefony) -> zakladka Osoby kolumna C
// Usunieto duplikaty, posortowano alfabetycznie

function getImportOsoby() {
  return [
    { "imie": "Anton Larin", "telefon": "" },
    { "imie": "Binienda Adrian", "telefon": "531093655" },
    { "imie": "Burda Kamil", "telefon": "733731800" },
    { "imie": "Bąk Andrzej", "telefon": "690569443" },
    { "imie": "Chmiel Dominik", "telefon": "" },
    { "imie": "Chmiel Janusz", "telefon": "733853668" },
    { "imie": "Chmiel Karol (K)", "telefon": "570400696" },
    { "imie": "Ciastoch Damian (k)", "telefon": "729332900" },
    { "imie": "Czerepak Ireneusz", "telefon": "" },
    { "imie": "Czuchra Paweł", "telefon": "794557048" },
    { "imie": "Daczyński Bartłomiej", "telefon": "" },
    { "imie": "Duszyński Janusz", "telefon": "732928395" },
    { "imie": "Huta Artur", "telefon": "782129452" },
    { "imie": "Jamroży Marcin", "telefon": "" },
    { "imie": "Jankiel Krystian", "telefon": "797557048" },
    { "imie": "Jaświecki Tomasz (K)", "telefon": "663668789" },
    { "imie": "Jurczuk Kacper", "telefon": "731080563" },
    { "imie": "Juszko Tomasz (k)", "telefon": "" },
    { "imie": "Kaczmarek Kamil (k)", "telefon": "663012997" },
    { "imie": "Kava Ruslan", "telefon": "" },
    { "imie": "Krzysztof Lesner", "telefon": "695144954" },
    { "imie": "Kłosowski Bartosz", "telefon": "" },
    { "imie": "Lewandowski Sebastian", "telefon": "668173395" },
    { "imie": "Leśniewski Szymon", "telefon": "" },
    { "imie": "Machowski Samuel", "telefon": "" },
    { "imie": "Majewski Karol", "telefon": "" },
    { "imie": "Martyniuk Andrii", "telefon": "787035865" },
    { "imie": "Mazek Mateusz", "telefon": "790893018" },
    { "imie": "Mielniczek Daniel (k)", "telefon": "505 603 906" },
    { "imie": "Mądro Aleksander", "telefon": "578212251" },
    { "imie": "Noga Jacek", "telefon": "" },
    { "imie": "Nowaczek Kamil", "telefon": "" },
    { "imie": "Nowak Daniel", "telefon": "733173609" },
    { "imie": "Okilka Ihor", "telefon": "510161442" },
    { "imie": "Ołęg Jakub (K)", "telefon": "784335855" },
    { "imie": "Partyka Igor", "telefon": "" },
    { "imie": "Pałucki Kamil", "telefon": "" },
    { "imie": "Polit Tomasz", "telefon": "531 148 191" },
    { "imie": "Porczyk Michał (k)", "telefon": "" },
    { "imie": "Płonka Krzysztof", "telefon": "" },
    { "imie": "Rdest Patryk", "telefon": "781430836" },
    { "imie": "Sadkowski Mariusz (K)", "telefon": "732808113" },
    { "imie": "Siedlecki Patryk", "telefon": "" },
    { "imie": "Sijka Damian", "telefon": "607127088" },
    { "imie": "Simlat Mariusz", "telefon": "663832184" },
    { "imie": "Sochacki Krzysztof", "telefon": "" },
    { "imie": "Stankiewicz Kamil", "telefon": "882192786" },
    { "imie": "Stechnij Kamil (K)", "telefon": "733853668" },
    { "imie": "Suchodolski Marek", "telefon": "" },
    { "imie": "Suski Michał", "telefon": "" },
    { "imie": "Szybowski Bogusław", "telefon": "536920333" },
    { "imie": "Trzęniowski Marcin", "telefon": "" },
    { "imie": "Tykholaz Ihor", "telefon": "" },
    { "imie": "Vronskyi Oleksandr", "telefon": "" },
    { "imie": "Wasylczuk Kacper", "telefon": "512757406" },
    { "imie": "Wdowski Łukasz", "telefon": "451281491" },
    { "imie": "Yevhenii Kutsenko", "telefon": "" },
    { "imie": "Zacharko Krzysztof", "telefon": "" },
    { "imie": "Zakrzacki Dominik", "telefon": "516804136" },
    { "imie": "Zhazhko Oleksandr (k)", "telefon": "" },
    { "imie": "Zubik Damian (k)", "telefon": "536976658" },
    { "imie": "Śląsiadek Maciej", "telefon": "791314756" },
    { "imie": "Śmieszek Sebastian", "telefon": "501140181" }
  ];
}